{
    "作者": "乐哥",
    "站名": "红果短剧",
    "编码": "UTF-8",
    "请求头": "User-Agent$MOBILE_UA",
    "主页url": "https://mov.cenguigui.cn/duanju/api.php?name=%E6%80%BB%E8%A3%81",
    "首页": "200",
    "起始页": "1",
    "嗅探": "0",
    "分类url": "https://mov.cenguigui.cn/duanju/api.php?name={cateId}&page={catePg}&tab_type=19;;m0",
    "分类": "大唐&大秦&大明&擦边&逆袭&霸总&豪门恩怨&神豪&都市日常&大女主&都市修仙&强者回归&重生&闪婚&赘婿逆袭&追妻&萌宝&奇幻脑洞&传承觉醒&奇幻爱情&乡村&历史古代&王妃&娱乐圈&暗恋成真&系统&真假千金&穿书&女帝&团宠&年代爱情&玄幻仙侠&皇后&替身",
    "数组": "data",
    "图片": "cover",
    "标题": "title",
    "副标题": "",
    "链接": "book_id",
    "链接前缀": "https://mov.cenguigui.cn/duanju/api.php?book_id=",
    "影片类型": "category\": \"&&\"",
    "状态": "duration\": \"&&\"",
    "主演": "author\": \"&&\"",
    "简介": "【友情提醒：请不要相信视频中的广告，以免上当受骗！】✨乐哥为您介绍剧情👉+desc\": \"&&\"",
    "线路数组": "",
    "线路标题": "红果专线",
    "播放二次截取": "",
    "播放数组": "\\[&&\\]",
    "播放列表": "{&&}",
    "播放标题": "title\": \"&&\"",
    "倒叙":";;1",
    "播放链接": "video_id\": \"&&\"",
    "播放链接前缀": "https://mov.cenguigui.cn/duanju/api.php?video_id=",
    "直接播放": "0",
    "二次跳转播放链接": "url\":\"&&\"",
    "嗅探词": "",
    "搜索请求头": "User-Agent$MOBILE_UA",
    "搜索url": "https://mov.cenguigui.cn/duanju/api.php?name={wd}page={pg}&tab_type=19",
    "搜索模式": "1",
    "搜索数组": "data",
    "搜索图片": "cover",
    "搜索标题": "title",
    "搜索链接": "book_id",
    "搜索链接前缀": "https://mov.cenguigui.cn/duanju/api.php?book_id="
}